import { StyleSheet } from "react-native";

const Styles = StyleSheet.create({
    filmsCardMainContainer: {
        width: '100%',
        marginVertical: 5,
        height: 'auto',
    },
    threeDotsContainer: {
        width: '100%',
        display: 'flex',
        alignItems: "center",
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        marginBottom: -40,
        marginTop: 15,
        zIndex: 100,
    },
    releaseDateContainer: {
        width: 'auto',
        height: 'auto',
        paddingHorizontal: 6,
        paddingVertical: 4,
        backgroundColor: '#00000070',
        borderRadius: 4,
    },
    releaseDateText: {
        fontFamily: 'Inter',
        fontWeight: '600',
        fontSize: 10,
        lineHeight: 16,
        color: '#ffffff',
    },
    cardImage: {
        width: '100%',
        height: 175,
        borderRadius: 6,
        objectFit: 'cover',
    },
    detailsContainer: {
        width: '100%',
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        zIndex: 100,
    },
    releasedStatusContainer: {
        width: 'auto',
        height: 'auto',
        paddingHorizontal: 10,
        paddingVertical: 4,
        backgroundColor: '#ffffff',
        borderRadius: 4,
        borderColor: "#D0D5DD",
        borderWidth: 0.5,
        marginVertical: 5,
    },
    releasedStatusText: {
        fontFamily: 'Inter',
        fontWeight: '500',
        fontSize: 12,
        lineHeight: 16,
        color: '#667085',
    },
    filmTitle: {
        fontFamily: 'Inter',
        fontWeight: '700',
        fontSize: 18,
        lineHeight: 24,
        color: '#252C32',
        marginVertical: 5,
    },
    filmDescription: {
        fontFamily: 'Inter',
        fontWeight: '400',
        fontSize: 14,
        lineHeight: 20,
        color: '#667085',
    },
    filmDirector: {
        fontFamily: 'Inter',
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 16,
        color: '#667085',
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#00000080',
      },
      modalView: {
        margin: 20,
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 35,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
      },
      button: {
        borderRadius: 20,
        padding: 10,
        elevation: 2,
      },
      buttonOpen: {
        backgroundColor: '#F194FF',
      },
      buttonClose: {
        backgroundColor: '#2196F3',
      },
      textStyle: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
      },
      mainModal: {
        backgroundColor: '#00000060',
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        display: 'flex',
      },
      modalText: {
        marginBottom: 15,
        textAlign: 'center',
      },
      modalContainer: {
        backgroundColor: '#ffffff',
        borderRadius: 4,
        width: '40%',
        display: 'flex',
      },
      listRow: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingVertical: 4,
        paddingHorizontal: 8,
        width: '100%',
      },
      listIcon: {
        marginRight: 5,
      },
      listText: {
        fontFamily: 'Inter',
        fontWeight: '500',
        letterSpacing: 0.5,
        fontSize: 12,
        lineHeight: 20,
        color: '#f1f1f5,'
      },
      deleteModalContainer: {
        backgroundColor: '#ffffff',
        borderRadius: 4,
        width: '75%',
        display: 'flex',
        padding: 20,
      },
      alertIcon: {
        marginBottom: 20,
      },
      cautionText: {
        fontFamily: 'Inter',
        fontWeight: '500',
        fontSize: 18,
        lineHeight: 28,
        color: '#101828'
      },
      confirmationMessage: {
        fontFamily: 'Inter',
      fontWeight: '500',
      fontSize: 14,
      lineHeight: 20,
        color: '#667085',
      },
      buttonsContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 30,
      },
      submitButtons: {
        width: '46%',
        borderRadius: 8,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 18,
        paddingVertical: 18,
        borderWidth: 1,
      },
      buttonText: {
        fontFamily: 'Inter',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 24,
      }
});

export default Styles;